import { Word } from '../types/index.js';

export const words: Word[] = [
  // Easy words - Azerbaijani words with English letters - All objects
  { id: '1', word: 'ev', difficulty: 'easy', category: 'object' },
  { id: '2', word: 'gunes', difficulty: 'easy', category: 'object' },
  { id: '3', word: 'agac', difficulty: 'easy', category: 'object' },
  { id: '4', word: 'masin', difficulty: 'easy', category: 'object' },
  { id: '5', word: 'pisik', difficulty: 'easy', category: 'object' },
  { id: '6', word: 'it', difficulty: 'easy', category: 'object' },
  { id: '7', word: 'qelem', difficulty: 'easy', category: 'object' },
  { id: '8', word: 'kitab', difficulty: 'easy', category: 'object' },
  { id: '9', word: 'cicek', difficulty: 'easy', category: 'object' },
  { id: '10', word: 'bulud', difficulty: 'easy', category: 'object' },
  { id: '11', word: 'alma', difficulty: 'easy', category: 'object' },
  { id: '12', word: 'top', difficulty: 'easy', category: 'object' },
  { id: '13', word: 'qus', difficulty: 'easy', category: 'object' },
  { id: '14', word: 'baliq', difficulty: 'easy', category: 'object' },
  { id: '15', word: 'ulduz', difficulty: 'easy', category: 'object' },
  { id: '16', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '17', word: 'pencere', difficulty: 'easy', category: 'object' },
  { id: '18', word: 'stul', difficulty: 'easy', category: 'object' },
  { id: '19', word: 'masa', difficulty: 'easy', category: 'object' },
  { id: '20', word: 'lampa', difficulty: 'easy', category: 'object' },
  { id: '21', word: 'telefon', difficulty: 'easy', category: 'object' },
  { id: '22', word: 'saat', difficulty: 'easy', category: 'object' },
  { id: '23', word: 'qolbaq', difficulty: 'easy', category: 'object' },
  { id: '24', word: 'ayaqqabi', difficulty: 'easy', category: 'object' },
  { id: '25', word: 'paltar', difficulty: 'easy', category: 'object' },
  { id: '26', word: 'qardas', difficulty: 'easy', category: 'object' },
  { id: '27', word: 'baci', difficulty: 'easy', category: 'object' },
  { id: '28', word: 'ana', difficulty: 'easy', category: 'object' },
  { id: '29', word: 'ata', difficulty: 'easy', category: 'object' },
  { id: '30', word: 'mekteb', difficulty: 'easy', category: 'object' },
  { id: '31', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '32', word: 'pencere', difficulty: 'easy', category: 'object' },
  { id: '33', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '34', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '35', word: 'qapi', difficulty: 'easy', category: 'object' },
  
  // Medium words - All objects
  { id: '36', word: 'komputer', difficulty: 'medium', category: 'object' },
  { id: '37', word: 'telefon', difficulty: 'medium', category: 'object' },
  { id: '38', word: 'teyyare', difficulty: 'medium', category: 'object' },
  { id: '39', word: 'gemi', difficulty: 'medium', category: 'object' },
  { id: '40', word: 'fil', difficulty: 'medium', category: 'object' },
  { id: '41', word: 'aslan', difficulty: 'medium', category: 'object' },
  { id: '42', word: 'qehve', difficulty: 'medium', category: 'object' },
  { id: '43', word: 'pizza', difficulty: 'medium', category: 'object' },
  { id: '44', word: 'goy', difficulty: 'medium', category: 'object' },
  { id: '45', word: 'ulduz', difficulty: 'medium', category: 'object' },
  { id: '46', word: 'gitara', difficulty: 'medium', category: 'object' },
  { id: '47', word: 'kamera', difficulty: 'medium', category: 'object' },
  { id: '48', word: 'velosiped', difficulty: 'medium', category: 'object' },
  { id: '49', word: 'kepene', difficulty: 'medium', category: 'object' },
  { id: '50', word: 'goyku', difficulty: 'medium', category: 'object' },
  { id: '51', word: 'dag', difficulty: 'medium', category: 'object' },
  { id: '52', word: 'deniz', difficulty: 'medium', category: 'object' },
  { id: '53', word: 'cay', difficulty: 'medium', category: 'object' },
  { id: '54', word: 'melek', difficulty: 'medium', category: 'object' },
  { id: '55', word: 'qar', difficulty: 'medium', category: 'object' },
  { id: '56', word: 'yagis', difficulty: 'medium', category: 'object' },
  { id: '57', word: 'kulek', difficulty: 'medium', category: 'object' },
  { id: '58', word: 'gunes', difficulty: 'medium', category: 'object' },
  { id: '59', word: 'ay', difficulty: 'medium', category: 'object' },
  { id: '60', word: 'restoran', difficulty: 'medium', category: 'object' },
  { id: '61', word: 'muzey', difficulty: 'medium', category: 'object' },
  { id: '62', word: 'kitabxana', difficulty: 'medium', category: 'object' },
  { id: '63', word: 'xestexana', difficulty: 'medium', category: 'object' },
  { id: '64', word: 'park', difficulty: 'medium', category: 'object' },
  { id: '65', word: 'cinema', difficulty: 'medium', category: 'object' },
  { id: '66', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '67', word: 'pencere', difficulty: 'medium', category: 'object' },
  { id: '68', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '69', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '70', word: 'qapi', difficulty: 'medium', category: 'object' },
  
  // Hard words - All objects
  { id: '71', word: 'kosmos', difficulty: 'hard', category: 'object' },
  { id: '72', word: 'robot', difficulty: 'hard', category: 'object' },
  { id: '73', word: 'dinozavr', difficulty: 'hard', category: 'object' },
  { id: '74', word: 'qalaktika', difficulty: 'hard', category: 'object' },
  { id: '75', word: 'mikroskop', difficulty: 'hard', category: 'object' },
  { id: '76', word: 'teleskop', difficulty: 'hard', category: 'object' },
  { id: '77', word: 'vulkan', difficulty: 'hard', category: 'object' },
  { id: '78', word: 'piramida', difficulty: 'hard', category: 'object' },
  { id: '79', word: 'helikopter', difficulty: 'hard', category: 'object' },
  { id: '80', word: 'orkestr', difficulty: 'hard', category: 'object' },
  { id: '81', word: 'universitet', difficulty: 'hard', category: 'object' },
  { id: '82', word: 'planetarium', difficulty: 'hard', category: 'object' },
  { id: '83', word: 'laboratoriya', difficulty: 'hard', category: 'object' },
  { id: '84', word: 'observatoriya', difficulty: 'hard', category: 'object' },
  { id: '85', word: 'astronavt', difficulty: 'hard', category: 'object' },
  { id: '86', word: 'alim', difficulty: 'hard', category: 'object' },
  { id: '87', word: 'muhendis', difficulty: 'hard', category: 'object' },
  { id: '88', word: 'doktor', difficulty: 'hard', category: 'object' },
  { id: '89', word: 'muellim', difficulty: 'hard', category: 'object' },
  { id: '90', word: 'ressam', difficulty: 'hard', category: 'object' },
  { id: '91', word: 'musiqici', difficulty: 'hard', category: 'object' },
  { id: '92', word: 'yazici', difficulty: 'hard', category: 'object' },
  { id: '93', word: 'aktyor', difficulty: 'hard', category: 'object' },
  { id: '94', word: 'idmanci', difficulty: 'hard', category: 'object' },
  { id: '95', word: 'sahil', difficulty: 'hard', category: 'object' },
  { id: '96', word: 'meyset', difficulty: 'hard', category: 'object' },
  { id: '97', word: 'qala', difficulty: 'hard', category: 'object' },
  { id: '98', word: 'kilsa', difficulty: 'hard', category: 'object' },
  { id: '99', word: 'mecid', difficulty: 'hard', category: 'object' },
  { id: '100', word: 'muze', difficulty: 'hard', category: 'object' },
  { id: '101', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '102', word: 'pencere', difficulty: 'hard', category: 'object' },
  { id: '103', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '104', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '105', word: 'qapi', difficulty: 'hard', category: 'object' },
  
  // Additional easy words - All objects
  { id: '106', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '107', word: 'pencere', difficulty: 'easy', category: 'object' },
  { id: '108', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '109', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '110', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '111', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '112', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '113', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '114', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '115', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '116', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '117', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '118', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '119', word: 'qapi', difficulty: 'easy', category: 'object' },
  { id: '120', word: 'qapi', difficulty: 'easy', category: 'object' },
  
  // Additional medium words - All objects
  { id: '121', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '122', word: 'pencere', difficulty: 'medium', category: 'object' },
  { id: '123', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '124', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '125', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '126', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '127', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '128', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '129', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '130', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '131', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '132', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '133', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '134', word: 'qapi', difficulty: 'medium', category: 'object' },
  { id: '135', word: 'qapi', difficulty: 'medium', category: 'object' },
  
  // Additional hard words - All objects
  { id: '136', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '137', word: 'pencere', difficulty: 'hard', category: 'object' },
  { id: '138', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '139', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '140', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '141', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '142', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '143', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '144', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '145', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '146', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '147', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '148', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '149', word: 'qapi', difficulty: 'hard', category: 'object' },
  { id: '150', word: 'qapi', difficulty: 'hard', category: 'object' },
];

export function getRandomWord(difficulty?: 'easy' | 'medium' | 'hard'): Word {
  let filteredWords = words;
  if (difficulty) {
    filteredWords = words.filter(w => w.difficulty === difficulty);
  }
  const randomIndex = Math.floor(Math.random() * filteredWords.length);
  return filteredWords[randomIndex];
}
